version: "3.9"
services:
  
  database:
    container_name: database
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5431:5432"
    networks:
      - nesjs-network
  prod:
    container_name: products-api
    build:
      context: .
      target: production
    depends_on: 
      - database
    ports:
      - ${PORT}:${PORT}
    restart: unless-stopped
    networks:
      - nesjs-network

networks:
  nesjs-network: