version: "3.9"
services:
  database:
    container_name: database
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5431:5432"
  prod:
    container_name: products-api
    build:
      context: .
      target: production
    depends_on: 
      - database
    environment:
      DB_HOST: database
    env_file: 
      - .env
    ports:
      - ${PORT}:${PORT}
    restart: unless-stopped